# Generated by Django 5.2.6 on 2025-09-25 13:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CartWatchLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, max_length=64)),
                ('phone', models.CharField(db_index=True, max_length=20)),
                ('cart_snapshot', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('CONVERTED', 'Converted'), ('CLOSED', 'Closed')], db_index=True, default='OPEN', max_length=16)),
                ('converted_order_id', models.CharField(blank=True, default='', max_length=64)),
                ('source_url', models.URLField(blank=True, default='')),
                ('user_agent', models.TextField(blank=True, default='')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_seen_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'CartWatch Lead',
                'verbose_name_plural': 'CartWatch Leads',
                'indexes': [models.Index(fields=['session_id', 'status'], name='cartwatch_c_session_6dd42b_idx'), models.Index(fields=['phone', 'status'], name='cartwatch_c_phone_e38784_idx')],
            },
        ),
    ]
