# Generated by Django 5.2.6 on 2025-09-17 10:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='variant',
            name='amazon_url',
            field=models.URLField(blank=True, help_text='Amazon listing URL for this SKU (optional)', max_length=500),
        ),
        migrations.AddField(
            model_name='variant',
            name='promo_end',
            field=models.DateTimeField(blank=True, help_text='Promo end (exclusive)', null=True),
        ),
        migrations.AddField(
            model_name='variant',
            name='promo_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Optional. If set with a valid window, this becomes active price during promo.', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='variant',
            name='promo_start',
            field=models.DateTimeField(blank=True, help_text='Promo start (inclusive)', null=True),
        ),
    ]
