# Generated by Django 5.2.6 on 2025-09-19 11:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_variant_amazon_url_variant_promo_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='fbt_defaults',
            field=models.ManyToManyField(blank=True, related_name='fbt_default_for', to='shop.product'),
        ),
        migrations.AddField(
            model_name='product',
            name='fbt_variant_strategy',
            field=models.CharField(choices=[('FIRST_IN_STOCK', 'First in stock'), ('SAME_ATTRIBUTE_MATCH', 'Same attribute match'), ('PRICE_NEAREST', 'Price nearest')], default='FIRST_IN_STOCK', max_length=32),
        ),
        migrations.CreateModel(
            name='FBTLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.PositiveIntegerField(default=10)),
                ('is_active', models.BooleanField(default=True)),
                ('source_variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fbt_links', to='shop.variant')),
                ('target_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='as_fbt_target_product', to='shop.product')),
                ('target_variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='as_fbt_target_variant', to='shop.variant')),
            ],
            options={
                'ordering': ['priority', 'id'],
                'constraints': [models.CheckConstraint(condition=models.Q(('target_product__isnull', True), ('target_variant__isnull', True), _negated=True), name='fbt_target_required')],
            },
        ),
    ]
