# Generated by Django 5.2.6 on 2025-09-20 12:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_product_fbt_defaults_product_fbt_variant_strategy_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True)),
                ('title', models.CharField(blank=True, default='', max_length=140)),
                ('notes', models.TextField(blank=True, default='')),
                ('type', models.CharField(choices=[('PERCENT', 'Percent'), ('FLAT', 'Flat')], max_length=16)),
                ('value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('max_discount_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('PAUSED', 'Paused'), ('EXPIRED', 'Expired')], default='ACTIVE', max_length=12)),
                ('applies_to', models.CharField(choices=[('CART', 'Cart'), ('PRODUCTS', 'Products'), ('CATEGORIES', 'Categories')], default='CART', max_length=16)),
                ('min_cart_subtotal', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('first_order_only', models.BooleanField(default=False)),
                ('per_user_limit', models.PositiveIntegerField(blank=True, null=True)),
                ('global_limit', models.PositiveIntegerField(blank=True, null=True)),
                ('is_public', models.BooleanField(default=True)),
                ('show_in_listing', models.BooleanField(default=True)),
                ('allow_deeplink', models.BooleanField(default=False)),
                ('vanity_slug', models.SlugField(blank=True, max_length=64, null=True)),
                ('is_stackable', models.BooleanField(default=False)),
                ('stack_group', models.CharField(blank=True, max_length=32, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('eligible_users', models.ManyToManyField(blank=True, related_name='eligible_coupons', to=settings.AUTH_USER_MODEL)),
                ('excluded_categories', models.ManyToManyField(blank=True, related_name='coupon_excluded_cat_set', to='shop.category')),
                ('excluded_products', models.ManyToManyField(blank=True, related_name='coupon_excluded_set', to='shop.product')),
                ('included_categories', models.ManyToManyField(blank=True, related_name='coupon_included_cat_set', to='shop.category')),
                ('included_products', models.ManyToManyField(blank=True, related_name='coupon_included_set', to='shop.product')),
            ],
        ),
        migrations.CreateModel(
            name='CouponAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('code_alias', models.CharField(blank=True, max_length=32, null=True, unique=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('redemption_limit', models.PositiveIntegerField(default=1)),
                ('redemptions_count', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True, default='')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='shop.coupon')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coupon_assignments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CouponRedemption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_reference', models.CharField(blank=True, default='', max_length=64)),
                ('session_id', models.CharField(blank=True, default='', max_length=64)),
                ('used_at', models.DateTimeField(auto_now_add=True)),
                ('amount_discounted', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('snapshot', models.JSONField(blank=True, default=dict)),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='redemptions', to='shop.coupon')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coupon_redemptions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='coupon',
            index=models.Index(fields=['code'], name='shop_coupon_code_ae6228_idx'),
        ),
        migrations.AddIndex(
            model_name='coupon',
            index=models.Index(fields=['status'], name='shop_coupon_status_4d2a55_idx'),
        ),
        migrations.AddIndex(
            model_name='coupon',
            index=models.Index(fields=['starts_at'], name='shop_coupon_starts__8afd3f_idx'),
        ),
        migrations.AddIndex(
            model_name='coupon',
            index=models.Index(fields=['ends_at'], name='shop_coupon_ends_at_554812_idx'),
        ),
        migrations.AddIndex(
            model_name='couponredemption',
            index=models.Index(fields=['used_at'], name='shop_coupon_used_at_23133e_idx'),
        ),
        migrations.AddIndex(
            model_name='couponredemption',
            index=models.Index(fields=['coupon', 'used_at'], name='shop_coupon_coupon__4b4484_idx'),
        ),
    ]
