# Generated by Django 5.2.6 on 2025-09-20 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_coupon_couponassignment_couponredemption_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='excluded_variants',
            field=models.ManyToManyField(blank=True, help_text='Variants to exclude even if product/category qualifies.', related_name='coupon_excluded_variant_set', to='shop.variant'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='included_variants',
            field=models.ManyToManyField(blank=True, help_text='If set, ONLY these variants qualify.', related_name='coupon_included_variant_set', to='shop.variant'),
        ),
    ]
