# Generated by Django 5.2.6 on 2025-09-20 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_coupon_excluded_variants_coupon_included_variants'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CouponAssignment',
        ),
    ]
