# Generated by Django 5.2.6 on 2025-09-24 13:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_delete_couponassignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='variant',
            name='delivery_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
