# Generated by Django 5.2.6 on 2025-09-30 09:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_variant_delivery_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchClickVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(db_index=True, max_length=128)),
                ('clicks', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_clicks', to='shop.variant')),
            ],
            options={
                'indexes': [models.Index(fields=['query', 'clicks'], name='shop_search_query_a83f64_idx')],
                'unique_together': {('query', 'variant')},
            },
        ),
        migrations.CreateModel(
            name='VariantStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('views', models.PositiveIntegerField(default=0)),
                ('clicks', models.PositiveIntegerField(default=0)),
                ('add_to_cart', models.PositiveIntegerField(default=0)),
                ('orders', models.PositiveIntegerField(default=0)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('variant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='shop.variant')),
            ],
            options={
                'indexes': [models.Index(fields=['orders', 'add_to_cart', 'clicks'], name='shop_varian_orders_5c27ae_idx')],
            },
        ),
    ]
