# Generated by Django 5.2.6 on 2025-09-30 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_searchclickvariant_variantstats'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('views', models.PositiveIntegerField(default=0)),
                ('clicks', models.PositiveIntegerField(default=0)),
                ('add_to_cart', models.PositiveIntegerField(default=0)),
                ('orders', models.PositiveIntegerField(default=0)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='shop.product')),
            ],
            options={
                'indexes': [models.Index(fields=['orders', 'add_to_cart', 'clicks'], name='shop_produc_orders_e37d76_idx')],
            },
        ),
        migrations.CreateModel(
            name='SearchClick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(db_index=True, max_length=128)),
                ('clicks', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_clicks', to='shop.product')),
            ],
            options={
                'indexes': [models.Index(fields=['query', 'clicks'], name='shop_search_query_95d10c_idx')],
                'unique_together': {('query', 'product')},
            },
        ),
    ]
