# Generated by Django 5.2.6 on 2025-10-02 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_productstats_searchclick'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, help_text='Ideal 600x600px, <200KB', null=True, upload_to='categories/%Y/%m/'),
        ),
    ]
