# Generated by Django 5.2.6 on 2025-10-03 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_category_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='badge',
        ),
        migrations.AddField(
            model_name='variant',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
