# Generated by Django 5.2.6 on 2025-10-04 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_alter_category_options_category_display_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='featured',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
