# Generated by Django 5.2.6 on 2025-10-08 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_remove_product_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='meta_title',
        ),
    ]
