# Generated by Django 5.2.6 on 2025-09-27 19:52

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(blank=True, max_length=120)),
                ('address_html', models.TextField(blank=True, help_text='You can use <br> for line breaks')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=60)),
                ('map_link', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='FooterSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('order', models.PositiveIntegerField(default=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=80)),
                ('url', models.CharField(help_text='Internal slug or external URL', max_length=255)),
                ('group', models.CharField(choices=[('PRIMARY', 'Primary (Header)'), ('UTILITY', 'Utility (Header small)'), ('FOOTER', 'Footer (flat list)')], default='PRIMARY', max_length=16)),
                ('new_tab', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=100)),
            ],
            options={
                'ordering': ('group', 'order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='SiteBranding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='branding/')),
                ('alt_text', models.CharField(default='Logo', max_length=120)),
                ('logo_link', models.CharField(default='/', max_length=255)),
                ('favicon', models.ImageField(blank=True, upload_to='branding/')),
            ],
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('network', models.CharField(choices=[('facebook', 'Facebook'), ('instagram', 'Instagram'), ('pinterest', 'Pinterest'), ('x', 'X (Twitter)')], max_length=20)),
                ('url', models.URLField()),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=100)),
            ],
            options={
                'ordering': ('order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='TopBarMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=180)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=100)),
                ('start_at', models.DateTimeField(blank=True, null=True)),
                ('end_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ('order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='FooterLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=80)),
                ('url', models.CharField(max_length=255)),
                ('new_tab', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=100)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='siteconfig.footersection')),
            ],
            options={
                'ordering': ('section', 'order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='NewsletterSignup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator()])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source_url', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'ordering': ('-created_at',),
                'unique_together': {('email',)},
            },
        ),
    ]
