# Generated by Django 5.2.6 on 2025-09-27 20:07

import siteconfig.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteconfig', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitebranding',
            name='logo',
            field=models.ImageField(upload_to='branding/', validators=[siteconfig.models.validate_svg_or_raster]),
        ),
    ]
