# Generated by Django 5.2.6 on 2025-10-02 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siteconfig', '0002_alter_sitebranding_logo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sociallink',
            options={'ordering': ['order', 'id'], 'verbose_name': 'Social link', 'verbose_name_plural': 'Social links'},
        ),
    ]
