# Generated by Django 5.2.6 on 2025-09-26 10:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop', '0007_variant_delivery_price'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(db_index=True, max_length=24, unique=True)),
                ('status', models.CharField(choices=[('CREATED', 'Created'), ('PAID', 'Paid'), ('PARTIALLY_PAID', 'Partially paid'), ('CANCELLED', 'Cancelled'), ('FAILED', 'Failed')], default='CREATED', max_length=20)),
                ('full_name', models.CharField(max_length=120)),
                ('address_line', models.TextField()),
                ('city', models.CharField(max_length=80)),
                ('state', models.CharField(max_length=80)),
                ('pincode', models.CharField(max_length=10)),
                ('mobile', models.CharField(max_length=20)),
                ('item_total', models.PositiveIntegerField(help_text='Subtotal in paise')),
                ('discount_total', models.PositiveIntegerField(default=0, help_text='Discount in paise')),
                ('shipping_total', models.PositiveIntegerField(default=0, help_text='Shipping in paise')),
                ('care_fee', models.PositiveIntegerField(default=0, help_text='Care/handling in paise')),
                ('grand_total', models.PositiveIntegerField(help_text='Final payable in paise')),
                ('coupon_code', models.CharField(blank=True, max_length=50, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('amount_paid', models.PositiveIntegerField(default=0, help_text='Total paid so far (in paise)')),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('variant_text', models.CharField(blank=True, max_length=200)),
                ('qty', models.PositiveIntegerField()),
                ('unit_price', models.PositiveIntegerField(help_text='Unit price in paise')),
                ('line_total', models.PositiveIntegerField(help_text='Line total in paise')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shop.product')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='shop.variant')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('razorpay', 'Razorpay'), ('payu', 'PayU'), ('upi_hdfc_any', 'UPI Promo (HDFC/any)'), ('semi_cod', 'Semi-COD')], max_length=20)),
                ('status', models.CharField(choices=[('INITIATED', 'Initiated'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], default='INITIATED', max_length=20)),
                ('amount', models.PositiveIntegerField(help_text='Attempt amount in paise')),
                ('provider_order_id', models.CharField(blank=True, max_length=100, null=True)),
                ('provider_payment_id', models.CharField(blank=True, max_length=100, null=True)),
                ('provider_signature', models.CharField(blank=True, max_length=200, null=True)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='orders.order')),
            ],
        ),
    ]
