# Generated by Django 5.2.6 on 2025-09-26 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_remove_order_care_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='gstin',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
