# .github/workflows/deploy.yml
name: Deploy to EC2

on:
  push:
    branches: ["main"]   # yahan apna branch rakhna

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (for completeness)
        uses: actions/checkout@v4

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add EC2 to known_hosts
        run: |
          ssh-keyscan -H "${{ secrets.EC2_HOST }}" >> ~/.ssh/known_hosts

      - name: Remote deploy
        env:
          HOST: ${{ secrets.EC2_HOST }}
          USER: ${{ secrets.EC2_USER }}
        run: |
          ssh -o StrictHostKeyChecking=yes $USER@$HOST '/srv/webapp/deploy.sh'
